export const primitiveTokens = {
  colors: {
    black: '#000',
    white: '#fff',
    primaryEmerald: {
      50: '#F4F9E6',
      300: '#A3E066',
      400: '#85D633',
      500: '#66CC00'
    },
    primaryBlue: {
      50: '#E5E8EE',
      100: '#CCD3DD',
      200: '#99A7BB',
      300: '#7F90AA',
      400: '#667A99',
      500: '#4D6588',
      600: '#334E77',
      700: '#1A3966',
      800: '#002255'
    },
    secondaryOrange: {
      100: '#FFE6CC',
      200: '#FFCD99',
      300: '#FFB566',
      400: '#FF9C33',
      500: '#FF8300'
    },
    pink: {
      50: '#FEE3EE',
      100: '#FDB8D5',
      200: '#fbcfe8',
      300: '#FE539C',
      400: '#FE1284',
      500: '#FF006B',
      600: '#ED0069',
      700: '#D60064',
      800: '#C10061',
      900: '#9A005B'
    },
    violet: {
      50: '#FAF5FF',
      100: '#F3E8FF',
      200: '#E9D5FF',
      300: '#D8B4FE',
      400: '#BC05FF',
      500: '#AE00FD',
      600: '#9900F8',
      700: '#7A00F3',
      800: '#5A00F0',
      900: '#0000E5'
    },
    indigo: {
      50: '#E9EAF6',
      100: '#C7CAE9',
      200: '#A3A8D9',
      300: '#7F86CA',
      400: '#646BBE',
      500: '#4B50B3',
      600: '#4548A9',
      700: '#3C3E9D',
      800: '#353491',
      900: '#28227C'
    },
    blue: {
      50: '#E5E8EE',
      100: '#CCD3DD',
      200: '#99A7BB',
      300: '#7F90AA',
      400: '#667A99',
      500: '#4D6588',
      600: '#334E77',
      700: '#1A3966',
      800: '#002255'
    },
    emerald: {
      50: '#F4F9E6',
      300: '#A3E066',
      400: '#85D633',
      500: '#66CC00'
    },
    amber: {
      50: '#FFFCE5',
      100: '#FFF6BF',
      200: '#FFF193',
      300: '#FFEB67',
      400: '#FEE641',
      500: '#FFE312',
      600: '#FED00D',
      700: '#FCB804',
      800: '#FB9F00',
      900: '#F97300'
    },
    orange: {
      100: '#FFE6CC',
      200: '#FFCD99',
      300: '#FFB566',
      400: '#FF9C33',
      500: '#FF8300'
    },
    red: {
      50: '#FDEBED',
      100: '#FBCDCF',
      200: '#E79B96',
      300: '#DA766E',
      400: '#E25A4A',
      500: '#E44F30',
      600: '#D6452F',
      700: '#C43C2A',
      800: '#B73623',
      900: '#A82E19'
    },
    gray: {
      50: '#F9FAFB',
      100: '#F3F4F6',
      150: '#EEEFF0',
      200: '#E5E7EB',
      300: '#D1D5DB',
      400: '#9CA3AF',
      433: '#8C939F',
      450: '#848B98',
      466: '#7B8290',
      500: '#6B7280',
      600: '#4B5563',
      700: '#374151',
      800: '#1F2937',
      900: '#111827'
    },
    brandGreen: '#66CC00',
    brandBlue: '#002255',
    brandOrange: '#FF8300',
    neutral: {
      0: '#fff',
      100: '#F9FAFB',
      200: '#EEEFF0',
      300: '#E5E7EB',
      400: '#D1D5DB',
      500: '#9CA3AF',
      600: '#6B7280',
      700: '#4B5563',
      800: '#1F2937',
      900: '#111827'
    }
  },
  breakpoints: {
    xs: '480px',
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px'
  },
  spacing: {
    none: '0',
    xs: '.25rem',
    sm: '.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
    '4xl': '6rem',
    '5xl': '8rem'
  },
  borderWidth: {
    none: '0',
    thin: '1px',
    medium: '2px',
    thick: '4px',
    heavy: '8px'
  },
  borderRadius: {
    none: '0px',
    xs: '2px',
    sm: '4px',
    md: '6px',
    lg: '8px',
    xl: '12px',
    '2xl': '16px',
    '3xl': '24px',
    full: '9999px'
  },
  typography: {
    fontFamilyPrimary: 'Poppins, system-ui, -apple-system, sans-serif',
    fontFamilyHeading: 'Poppins, system-ui, -apple-system, sans-serif',
    fontFamilyMono: 'ui-monospace, "SF Mono", "Monaco", "Inconsolata", "Roboto Mono", monospace',
    fontSize: {
      xs: '.75rem',
      sm: '.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '3.75rem'
    },
    fontWeight: {
      thin: '100',
      extralight: '200',
      light: '300',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
      black: '900'
    },
    lineHeight: {
      tight: '1.25',
      snug: '1.375',
      normal: '1.5',
      relaxed: '1.625',
      loose: '2'
    }
  }
} as const;

export type ThemeMode = 'light' | 'dark';

export const semanticThemes = {
  light: {
    colors: {
      border: primitiveTokens.colors.gray[200],
      backgroundBase: primitiveTokens.colors.gray[50],
      backgroundSurface: primitiveTokens.colors.white,
      backgroundElevated: primitiveTokens.colors.white,
      textBase: primitiveTokens.colors.gray[900],
      textMuted: primitiveTokens.colors.gray[500],
      textOnPrimary: primitiveTokens.colors.white,
      accent: primitiveTokens.colors.secondaryOrange[500],
      actionPrimary: primitiveTokens.colors.primaryEmerald[500],
      actionSecondary: primitiveTokens.colors.primaryBlue[800],
      actionDanger: primitiveTokens.colors.red[500],
      statusSuccess: primitiveTokens.colors.primaryEmerald[500],
      statusWarning: primitiveTokens.colors.amber[500],
      statusError: primitiveTokens.colors.red[500],
      overlayScrim: 'rgba(0, 0, 0, 0.5)',
      overlayHover: 'rgba(0, 34, 85, 0.04)',
      overlayActive: 'rgba(0, 34, 85, 0.08)',
      overlayFocus: 'rgba(0, 34, 85, 0.24)'
    },
    effects: {
      shadowSm: '0 10px 24px rgba(0, 34, 85, 0.12)',
      shadowMd: '0 20px 40px rgba(0, 34, 85, 0.16)',
      shellGradient: 'linear-gradient(180deg, #F9FAFB 0%, #E5E8EE 100%)'
    }
  },
  dark: {
    colors: {
      border: primitiveTokens.colors.primaryBlue[600],
      backgroundBase: primitiveTokens.colors.primaryBlue[800],
      backgroundSurface: primitiveTokens.colors.gray[900],
      backgroundElevated: primitiveTokens.colors.gray[800],
      textBase: primitiveTokens.colors.white,
      textMuted: primitiveTokens.colors.gray[300],
      textOnPrimary: primitiveTokens.colors.white,
      accent: primitiveTokens.colors.secondaryOrange[400],
      actionPrimary: primitiveTokens.colors.primaryEmerald[400],
      actionSecondary: primitiveTokens.colors.primaryBlue[500],
      actionDanger: primitiveTokens.colors.red[400],
      statusSuccess: primitiveTokens.colors.primaryEmerald[400],
      statusWarning: primitiveTokens.colors.amber[400],
      statusError: primitiveTokens.colors.red[400],
      overlayScrim: 'rgba(0, 0, 0, 0.68)',
      overlayHover: 'rgba(255, 255, 255, 0.06)',
      overlayActive: 'rgba(255, 255, 255, 0.12)',
      overlayFocus: 'rgba(133, 214, 51, 0.34)'
    },
    effects: {
      shadowSm: '0 12px 24px rgba(0, 0, 0, 0.35)',
      shadowMd: '0 24px 48px rgba(0, 0, 0, 0.42)',
      shellGradient: 'linear-gradient(180deg, #002255 0%, #111827 100%)'
    }
  }
} as const;

export const semanticTokens = semanticThemes.light;

export type ThemeVariables = Record<`--${string}`, string>;

export function createThemeVariables(mode: ThemeMode = 'light', overrides: Partial<ThemeVariables> = {}): ThemeVariables {
  const semanticTokens = semanticThemes[mode];

  return {
    '--primary-emerald-500': primitiveTokens.colors.primaryEmerald[500],
    '--primary-emerald-400': primitiveTokens.colors.primaryEmerald[400],
    '--primary-emerald-300': primitiveTokens.colors.primaryEmerald[300],
    '--primary-emerald-50': primitiveTokens.colors.primaryEmerald[50],
    '--primary-blue-800': primitiveTokens.colors.primaryBlue[800],
    '--primary-blue-700': primitiveTokens.colors.primaryBlue[700],
    '--primary-blue-600': primitiveTokens.colors.primaryBlue[600],
    '--primary-blue-500': primitiveTokens.colors.primaryBlue[500],
    '--primary-blue-400': primitiveTokens.colors.primaryBlue[400],
    '--primary-blue-300': primitiveTokens.colors.primaryBlue[300],
    '--primary-blue-200': primitiveTokens.colors.primaryBlue[200],
    '--primary-blue-100': primitiveTokens.colors.primaryBlue[100],
    '--primary-blue-50': primitiveTokens.colors.primaryBlue[50],
    '--secondary-orange-500': primitiveTokens.colors.secondaryOrange[500],
    '--secondary-orange-400': primitiveTokens.colors.secondaryOrange[400],
    '--secondary-orange-300': primitiveTokens.colors.secondaryOrange[300],
    '--secondary-orange-200': primitiveTokens.colors.secondaryOrange[200],
    '--secondary-orange-100': primitiveTokens.colors.secondaryOrange[100],
    '--black': primitiveTokens.colors.black,
    '--white': primitiveTokens.colors.white,
    '--pink-50': primitiveTokens.colors.pink[50],
    '--pink-100': primitiveTokens.colors.pink[100],
    '--pink-200': primitiveTokens.colors.pink[200],
    '--pink-300': primitiveTokens.colors.pink[300],
    '--pink-400': primitiveTokens.colors.pink[400],
    '--pink-500': primitiveTokens.colors.pink[500],
    '--pink-600': primitiveTokens.colors.pink[600],
    '--pink-700': primitiveTokens.colors.pink[700],
    '--pink-800': primitiveTokens.colors.pink[800],
    '--pink-900': primitiveTokens.colors.pink[900],
    '--violet-50': primitiveTokens.colors.violet[50],
    '--violet-100': primitiveTokens.colors.violet[100],
    '--violet-200': primitiveTokens.colors.violet[200],
    '--violet-300': primitiveTokens.colors.violet[300],
    '--violet-400': primitiveTokens.colors.violet[400],
    '--violet-500': primitiveTokens.colors.violet[500],
    '--violet-600': primitiveTokens.colors.violet[600],
    '--violet-700': primitiveTokens.colors.violet[700],
    '--violet-800': primitiveTokens.colors.violet[800],
    '--violet-900': primitiveTokens.colors.violet[900],
    '--indigo-50': primitiveTokens.colors.indigo[50],
    '--indigo-100': primitiveTokens.colors.indigo[100],
    '--indigo-200': primitiveTokens.colors.indigo[200],
    '--indigo-300': primitiveTokens.colors.indigo[300],
    '--indigo-400': primitiveTokens.colors.indigo[400],
    '--indigo-500': primitiveTokens.colors.indigo[500],
    '--indigo-600': primitiveTokens.colors.indigo[600],
    '--indigo-700': primitiveTokens.colors.indigo[700],
    '--indigo-800': primitiveTokens.colors.indigo[800],
    '--indigo-900': primitiveTokens.colors.indigo[900],
    '--blue-50': primitiveTokens.colors.blue[50],
    '--blue-100': primitiveTokens.colors.blue[100],
    '--blue-200': primitiveTokens.colors.blue[200],
    '--blue-300': primitiveTokens.colors.blue[300],
    '--blue-400': primitiveTokens.colors.blue[400],
    '--blue-500': primitiveTokens.colors.blue[500],
    '--blue-600': primitiveTokens.colors.blue[600],
    '--blue-700': primitiveTokens.colors.blue[700],
    '--blue-800': primitiveTokens.colors.blue[800],
    '--emerald-50': primitiveTokens.colors.emerald[50],
    '--emerald-300': primitiveTokens.colors.emerald[300],
    '--emerald-400': primitiveTokens.colors.emerald[400],
    '--emerald-500': primitiveTokens.colors.emerald[500],
    '--amber-50': primitiveTokens.colors.amber[50],
    '--amber-100': primitiveTokens.colors.amber[100],
    '--amber-200': primitiveTokens.colors.amber[200],
    '--amber-300': primitiveTokens.colors.amber[300],
    '--amber-400': primitiveTokens.colors.amber[400],
    '--amber-500': primitiveTokens.colors.amber[500],
    '--amber-600': primitiveTokens.colors.amber[600],
    '--amber-700': primitiveTokens.colors.amber[700],
    '--amber-800': primitiveTokens.colors.amber[800],
    '--amber-900': primitiveTokens.colors.amber[900],
    '--orange-100': primitiveTokens.colors.orange[100],
    '--orange-200': primitiveTokens.colors.orange[200],
    '--orange-300': primitiveTokens.colors.orange[300],
    '--orange-400': primitiveTokens.colors.orange[400],
    '--orange-500': primitiveTokens.colors.orange[500],
    '--red-50': primitiveTokens.colors.red[50],
    '--red-100': primitiveTokens.colors.red[100],
    '--red-200': primitiveTokens.colors.red[200],
    '--red-300': primitiveTokens.colors.red[300],
    '--red-400': primitiveTokens.colors.red[400],
    '--red-500': primitiveTokens.colors.red[500],
    '--red-600': primitiveTokens.colors.red[600],
    '--red-700': primitiveTokens.colors.red[700],
    '--red-800': primitiveTokens.colors.red[800],
    '--red-900': primitiveTokens.colors.red[900],
    '--gray-50': primitiveTokens.colors.gray[50],
    '--gray-100': primitiveTokens.colors.gray[100],
    '--gray-150': primitiveTokens.colors.gray[150],
    '--gray-200': primitiveTokens.colors.gray[200],
    '--gray-300': primitiveTokens.colors.gray[300],
    '--gray-400': primitiveTokens.colors.gray[400],
    '--gray-433': primitiveTokens.colors.gray[433],
    '--gray-450': primitiveTokens.colors.gray[450],
    '--gray-466': primitiveTokens.colors.gray[466],
    '--gray-500': primitiveTokens.colors.gray[500],
    '--gray-600': primitiveTokens.colors.gray[600],
    '--gray-700': primitiveTokens.colors.gray[700],
    '--gray-800': primitiveTokens.colors.gray[800],
    '--gray-900': primitiveTokens.colors.gray[900],
    '--colors-brand-green': primitiveTokens.colors.brandGreen,
    '--colors-brand-blue': primitiveTokens.colors.brandBlue,
    '--colors-brand-orange': primitiveTokens.colors.brandOrange,
    '--colors-brand-green-100': primitiveTokens.colors.primaryEmerald[50],
    '--colors-brand-green-200': primitiveTokens.colors.primaryEmerald[300],
    '--colors-brand-green-300': primitiveTokens.colors.primaryEmerald[400],
    '--colors-brand-green-400': primitiveTokens.colors.primaryEmerald[500],
    '--colors-brand-green-500': primitiveTokens.colors.emerald[500],
    '--colors-brand-green-600': primitiveTokens.colors.emerald[500],
    '--colors-brand-green-700': primitiveTokens.colors.emerald[400],
    '--colors-brand-green-800': primitiveTokens.colors.emerald[300],
    '--colors-brand-green-900': primitiveTokens.colors.emerald[50],
    '--colors-brand-blue-100': primitiveTokens.colors.primaryBlue[50],
    '--colors-brand-blue-200': primitiveTokens.colors.primaryBlue[100],
    '--colors-brand-blue-300': primitiveTokens.colors.primaryBlue[200],
    '--colors-brand-blue-400': primitiveTokens.colors.primaryBlue[300],
    '--colors-brand-blue-500': primitiveTokens.colors.primaryBlue[400],
    '--colors-brand-blue-600': primitiveTokens.colors.primaryBlue[500],
    '--colors-brand-blue-700': primitiveTokens.colors.primaryBlue[600],
    '--colors-brand-blue-800': primitiveTokens.colors.primaryBlue[700],
    '--colors-brand-blue-900': primitiveTokens.colors.primaryBlue[800],
    '--colors-brand-orange-100': primitiveTokens.colors.secondaryOrange[100],
    '--colors-brand-orange-200': primitiveTokens.colors.secondaryOrange[200],
    '--colors-brand-orange-300': primitiveTokens.colors.secondaryOrange[300],
    '--colors-brand-orange-400': primitiveTokens.colors.secondaryOrange[400],
    '--colors-brand-orange-500': primitiveTokens.colors.secondaryOrange[500],
    '--colors-brand-orange-600': primitiveTokens.colors.orange[500],
    '--colors-brand-orange-700': primitiveTokens.colors.orange[400],
    '--colors-brand-orange-800': primitiveTokens.colors.orange[300],
    '--colors-brand-orange-900': primitiveTokens.colors.orange[200],
    '--colors-neutral-0': primitiveTokens.colors.neutral[0],
    '--colors-neutral-100': primitiveTokens.colors.neutral[100],
    '--colors-neutral-200': primitiveTokens.colors.neutral[200],
    '--colors-neutral-300': primitiveTokens.colors.neutral[300],
    '--colors-neutral-400': primitiveTokens.colors.neutral[400],
    '--colors-neutral-500': primitiveTokens.colors.neutral[500],
    '--colors-neutral-600': primitiveTokens.colors.neutral[600],
    '--colors-neutral-700': primitiveTokens.colors.neutral[700],
    '--colors-neutral-800': primitiveTokens.colors.neutral[800],
    '--colors-neutral-900': primitiveTokens.colors.neutral[900],
    '--breakpoints-xs': primitiveTokens.breakpoints.xs,
    '--breakpoints-sm': primitiveTokens.breakpoints.sm,
    '--breakpoints-md': primitiveTokens.breakpoints.md,
    '--breakpoints-lg': primitiveTokens.breakpoints.lg,
    '--breakpoints-xl': primitiveTokens.breakpoints.xl,
    '--breakpoints-2xl': primitiveTokens.breakpoints['2xl'],
    '--spacing-none': primitiveTokens.spacing.none,
    '--spacing-xs': primitiveTokens.spacing.xs,
    '--spacing-sm': primitiveTokens.spacing.sm,
    '--spacing-md': primitiveTokens.spacing.md,
    '--spacing-lg': primitiveTokens.spacing.lg,
    '--spacing-xl': primitiveTokens.spacing.xl,
    '--spacing-2xl': primitiveTokens.spacing['2xl'],
    '--spacing-3xl': primitiveTokens.spacing['3xl'],
    '--spacing-4xl': primitiveTokens.spacing['4xl'],
    '--spacing-5xl': primitiveTokens.spacing['5xl'],
    '--border-width-none': primitiveTokens.borderWidth.none,
    '--border-width-thin': primitiveTokens.borderWidth.thin,
    '--border-width-medium': primitiveTokens.borderWidth.medium,
    '--border-width-thick': primitiveTokens.borderWidth.thick,
    '--border-width-heavy': primitiveTokens.borderWidth.heavy,
    '--border-radius-none': primitiveTokens.borderRadius.none,
    '--border-radius-xs': primitiveTokens.borderRadius.xs,
    '--border-radius-sm': primitiveTokens.borderRadius.sm,
    '--border-radius-md': primitiveTokens.borderRadius.md,
    '--border-radius-lg': primitiveTokens.borderRadius.lg,
    '--border-radius-xl': primitiveTokens.borderRadius.xl,
    '--border-radius-2xl': primitiveTokens.borderRadius['2xl'],
    '--border-radius-3xl': primitiveTokens.borderRadius['3xl'],
    '--border-radius-full': primitiveTokens.borderRadius.full,
    '--typography-font-family-primary': primitiveTokens.typography.fontFamilyPrimary,
    '--typography-font-family-heading': primitiveTokens.typography.fontFamilyHeading,
    '--typography-font-family-mono': primitiveTokens.typography.fontFamilyMono,
    '--typography-font-size-xs': primitiveTokens.typography.fontSize.xs,
    '--typography-font-size-sm': primitiveTokens.typography.fontSize.sm,
    '--typography-font-size-base': primitiveTokens.typography.fontSize.base,
    '--typography-font-size-lg': primitiveTokens.typography.fontSize.lg,
    '--typography-font-size-xl': primitiveTokens.typography.fontSize.xl,
    '--typography-font-size-2xl': primitiveTokens.typography.fontSize['2xl'],
    '--typography-font-size-3xl': primitiveTokens.typography.fontSize['3xl'],
    '--typography-font-size-4xl': primitiveTokens.typography.fontSize['4xl'],
    '--typography-font-size-5xl': primitiveTokens.typography.fontSize['5xl'],
    '--typography-font-size-6xl': primitiveTokens.typography.fontSize['6xl'],
    '--typography-font-weight-thin': primitiveTokens.typography.fontWeight.thin,
    '--typography-font-weight-extralight': primitiveTokens.typography.fontWeight.extralight,
    '--typography-font-weight-light': primitiveTokens.typography.fontWeight.light,
    '--typography-font-weight-normal': primitiveTokens.typography.fontWeight.normal,
    '--typography-font-weight-medium': primitiveTokens.typography.fontWeight.medium,
    '--typography-font-weight-semibold': primitiveTokens.typography.fontWeight.semibold,
    '--typography-font-weight-bold': primitiveTokens.typography.fontWeight.bold,
    '--typography-font-weight-extrabold': primitiveTokens.typography.fontWeight.extrabold,
    '--typography-font-weight-black': primitiveTokens.typography.fontWeight.black,
    '--typography-line-height-tight': primitiveTokens.typography.lineHeight.tight,
    '--typography-line-height-snug': primitiveTokens.typography.lineHeight.snug,
    '--typography-line-height-normal': primitiveTokens.typography.lineHeight.normal,
    '--typography-line-height-relaxed': primitiveTokens.typography.lineHeight.relaxed,
    '--typography-line-height-loose': primitiveTokens.typography.lineHeight.loose,
    '--colors-border': semanticTokens.colors.border,
    '--colors-background-base': semanticTokens.colors.backgroundBase,
    '--colors-background-surface': semanticTokens.colors.backgroundSurface,
    '--colors-background-elevated': semanticTokens.colors.backgroundElevated,
    '--colors-text-base': semanticTokens.colors.textBase,
    '--colors-text-muted': semanticTokens.colors.textMuted,
    '--colors-text-on-primary': semanticTokens.colors.textOnPrimary,
    '--colors-accent': semanticTokens.colors.accent,
    '--colors-action-primary': semanticTokens.colors.actionPrimary,
    '--colors-action-secondary': semanticTokens.colors.actionSecondary,
    '--colors-action-danger': semanticTokens.colors.actionDanger,
    '--colors-status-success': semanticTokens.colors.statusSuccess,
    '--colors-status-warning': semanticTokens.colors.statusWarning,
    '--colors-status-error': semanticTokens.colors.statusError,
    '--colors-overlay-scrim': semanticTokens.colors.overlayScrim,
    '--colors-overlay-hover': semanticTokens.colors.overlayHover,
    '--colors-overlay-active': semanticTokens.colors.overlayActive,
    '--colors-overlay-focus': semanticTokens.colors.overlayFocus,
    '--effects-shadow-sm': semanticTokens.effects.shadowSm,
    '--effects-shadow-md': semanticTokens.effects.shadowMd,
    '--effects-shell-gradient': semanticTokens.effects.shellGradient,
    ...overrides
  };
}

export const themeVariables = createThemeVariables('light');
export const darkThemeVariables = createThemeVariables('dark');

export function serializeThemeVariables(variables: ThemeVariables) {
  return Object.entries(variables)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n');
}

export function createThemeStyleSheet(overrides: Partial<ThemeVariables> = {}) {
  const lightVariables = createThemeVariables('light', overrides);
  const darkVariables = createThemeVariables('dark', overrides);

  return [
    "html[data-ui-theme='rapport'] {",
    serializeThemeVariables(lightVariables),
    '}',
    '',
    "html[data-ui-theme='rapport'][data-ui-mode='dark'] {",
    serializeThemeVariables(darkVariables),
    '}'
  ].join('\n');
}

export function tokenVar(name: `--${string}`, fallback?: string) {
  return fallback ? `var(${name}, ${fallback})` : `var(${name})`;
}
